### PR TITLE
adding zen garden tidying to tidying branch

### PR DESCRIPTION
**Pull request by anthony-gordon**

### CODE REVIEW

**Comment by RebDugNZ** [comment]
Hey so your tidying looks great.  The only thing I could see was the <p> tags.  On https://www.granneman.com/webdev/coding/formatting-and-indenting-your-html/ it says that the content should be indented on its own lines so you can see the open and close tags easier.

**Comment by anthony-gordon** [comment]
Thanks very much I've made those changes. have a look through and then go and merge if you like what you see :)

**Comment by RebDugNZ** [comment]
Hey, sorry to be a killjoy but I meant the content inside the p tags needed their own line.  Like in the resources they linked us:
Best method: indent text/content ↩
<p> 
    Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor
    incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud
    exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. 
</p>
Only reason I noticed is cause ALL my website code is like that and ill have to change it all :(

**Comment by anthony-gordon** [comment]
Oh right gotcha! Hahaha don't apologise this I need to know this stuff! All my code is too ahhh, time to go fix it all. Check it out again I think it's all set now

**Comment by RebDugNZ** [comment]
Awesome so that worked on my end so set me as a collaborator on yours and I'll merge and delete the tidy branch :)

**Pull request merged**
